# Netlify Deployment Configuration

[build]
  command = "npm run build"
  publish = ".next"

[functions]
  # Increase timeout for AI processing (max 15 minutes)
  max_age = 86400

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Environment variables (set in Netlify dashboard)
# GOOGLE_GENAI_API_KEY=your_api_key
# MONGODB_URI=your_mongodb_uri
# JWT_SECRET=your_jwt_secret